# Site settings
title: Computational Astrophysics

repository: weiguangcui/Computational_Astrophysics

course_name: Computational Astrophysics Course
course_description: "This MSc course aims at providing an introduction to high-performance computing using astrophysical phenonema as examples. The course is a mixture between actual class room lectures and hands-on coding exercises. It therefore is not only targetting the students from the astrophysics speciality of our MSc in Theoretical Physics, but rather of interest to all students."
course_semester: "Spring 2024"

baseurl: "/Computational_Astrophysics/" # the subpath of your site, e.g. /blog/
url: "https://github.com/weiguangcui/" # the base hostname & protocol for your site

schoolname: "UAM"
schoolurl: "https://uam.edu.es"
twitter_username: cuiweiguang

address: 01.15.SS.201 - Seminario Departamento Fisica Teorica.
    Facultad de Ciencias, Universidad Autonoma de Madrid
    Madrid
    Spain

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop', 'vendor']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    practice:
        output: true
    assignments:
        output: false
    announcements:
        output: false


# defaults:
#   - scope:
#       path: ""
#       type: "assignments"
#     values:
#       layout: "assignment"

plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false
